# Generated by Django 6.0.2 on 2026-03-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_classsubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='classes',
            field=models.ManyToManyField(related_name='exams', to='core.classroom'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
