# Generated by Django 6.0.2 on 2026-02-25 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_subject_unique_together_remove_subject_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='city',
        ),
    ]
