# Generated by Django 6.0.2 on 2026-03-22 12:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_exam_classes_alter_exam_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='exam',
            field=models.CharField(choices=[('Half Yearly', 'Half Yearly'), ('Final', 'Final')], max_length=50),
        ),
        migrations.RenameField(
            model_name='mark',
            old_name='marks',
            new_name='theory_marks',
        ),
        migrations.AlterUniqueTogether(
            name='mark',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='practical_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='theory_max',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='mark',
            name='practical_marks',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='mark',
            name='subject',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.classsubject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='school_logos/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.classroom'),
        ),
        migrations.AlterUniqueTogether(
            name='academicyear',
            unique_together={('school', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='mark',
            unique_together={('student', 'subject', 'exam')},
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
    ]
