# Generated by Django 6.0.2 on 2026-02-13 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_classroom_name_alter_classroom_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='classroom',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.classroom'),
            preserve_default=False,
        ),
    ]
