# Generated by Django 6.0.2 on 2026-02-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_school_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='registration_certificate',
            field=models.FileField(blank=True, null=True, upload_to='media/school_documents/'),
        ),
    ]
