# Generated by Django 6.0.2 on 2026-03-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_mark_exam_rename_marks_mark_theory_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsubject',
            name='full_marks',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='classsubject',
            name='practical_max',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='classsubject',
            name='theory_max',
            field=models.IntegerField(default=70),
        ),
    ]
