# Generated by Django 6.0.2 on 2026-03-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_student_address_student_father_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='principal_sign',
            field=models.ImageField(blank=True, null=True, upload_to='principal_signs/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_sign',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_signs/'),
        ),
    ]
