# Generated by Django 6.0.2 on 2026-03-27 15:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_school_principal_sign_teacher_teacher_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='registration_certificate',
            field=models.FileField(blank=True, null=True, upload_to='school_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
