# Generated by Django 6.0.2 on 2026-03-27 15:45

import cloudinary.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_school_registration_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='registration_certificate',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='registration_certificate'),
        ),
    ]
