# Generated by Django 6.0.2 on 2026-03-27 15:50

import cloudinary_storage.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_school_registration_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='registration_certificate',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='school_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
